export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED';

export const ORDERS_FETCH = 'ORDERS_FETCH';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAILED = 'ORDERS_FETCH_FAILED';
